### ISSUE TITLE
Defining “progressive”

### ISSUE THREAD

**Issue by adactio** [operasoftware/pwa-list#14]
Flipboard doesn't render anything at all if the initial JavaScript fails to load. Many others only display a non-functional shell.

I'm not convinced that many of the sites listed (apart from dev.opera.com, oumy.com and twitter.com) deserve to be labelled progressive when they're built on such fragile foundations.

(P.S. Flipkart is not being served over a secure connection. I can't seem to find the manifest file either.)

**Comment by PaulKinlan** [comment]
I don't disagree, the term "progressive" is loaded - Alex R's original post referred to it being Progressively installed as the user becomes more engaged.  I have certainly pushed more for ensuring that it works Progressively everywhere because I think that is the compelling story and helps us see this work for every user everywhere.

wrt to Flipkart, they made some choices about their mobile experience being the one they are working on and as such you need to emulate Chrome and now UC to get it to be on https and be installable.  It's not ideal, but they have a large legacy desktop experience that was hard to move across.  I suspect for a lot of large sites this is going to be a similar story unless they can re-do their entire experience in one go.

**Comment by andreasbovens** [comment]
https://github.com/operasoftware/pwa-list/blob/master/README.md has been updated, to better explain this. We'll be making some changes over the next couple of days, featuring additional sites, and unfeaturing others.
