### ISSUE TITLE
Split "real" sites from demo sites.

### ISSUE THREAD

**Issue by andreasbovens** [operasoftware/pwa-list#46]
The question is of course: what is real, what is a demo? We could go for a split like this:

# Real sites
- Dev.Opera
- Flipkart
- Pokedex 
- Soundslice 
- Oumy
- BaBe 
- The Session
- Firefox Platform Status
- Telegram
- Snapdrop
- Google I/O
- Currency Converter

# Demos
- Air Horner
- Emojoy
- Voice Memos 
- Wiki Offline 
- 2048 Puzzle 
- Get Kana!
- Wave-PD1 
- SVGOMG 
- QR Code Scanner
- PolyMail
- Guitar Tuner
- Inbox Attack
- WebNFC Shopping Cart 

@jkomoros @slightlyoff - thoughts?

**Comment by pepelsbey** [comment]
Air Horner is an app on its own domain that might be useful as an app to… you know… make sounds :) The same applies to many others: Get Kana, PD-1, etc. “Real app” definition is pretty subjective and vague.

**Comment by andreasbovens** [comment]
True, I'm also conflicted...

**Comment by jkomoros** [comment]
To me the question is: does the example operate as a _business_ or a service depended on by a large number of people? That is, will it be convincing to other businesses who want to know which _other_ businesses are on the Progressive Web App bandwagon?

So maybe "Demos" / "Real sites" is the wrong way of calling the other ones, since obviously a number of them are real sites.

@PaulKinlan as well

**Comment by shwetank** [comment]
I kind of agree with @jkomoros .... Rather than "Real Sites" and "Demos" (some might be both) ... I think it would be better to look at it as "Commercial or official web apps" of some organization and "personal technology demos" of an individual or small group. That way, I think, it would be easier to categorize the entries (as there would be little chance of overlap) rather than agonizing which ones are 'real sites' and which ones 'demos'.

**Comment by andreasbovens** [comment]
Fixed by various commits on April 28.
