### ISSUE TITLE
Suggestion: evernote

### ISSUE THREAD

**Issue by niwsa** [operasoftware/pwa-list#99]
https://www.evernote.com/Login.action

**Comment by pepelsbey** [comment]
It woudn’t look impressive for the most of users looking a for good PWA example because of the login screen. Though it might be a great PWA itself.

![www evernote com-login action galaxy s5](https://cloud.githubusercontent.com/assets/105274/17459040/34cc6cee-5c32-11e6-89da-bd1bb8a19642.png)

@andreasbovens @shwetank @mathiasbynens, what do you think?

**Comment by niwsa** [comment]
@pepelsbey Isn't that the same case for telegram?

**Comment by pepelsbey** [comment]
@niwsa, messengers audience is much bigger that Evernote’s one, maybe I'm wrong. Let's see what my colleagues think.

**Comment by zcdunn** [comment]
Evernote's website doesn't work on mobile browsers.

![evernote](https://cloud.githubusercontent.com/assets/7121969/17491214/a8bda5f8-5d74-11e6-871b-0ece9a700f7c.png)

**Comment by pepelsbey** [comment]
@niwsa, what’s the point then?
